{
 "title": "Postgres HA Chaos Lab Overview",
 "tags": [
  "postgres",
  "patroni",
  "chaos"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Primários Patroni",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(patroni_primary)" }
   ]
  },
  {
   "title": "Backup Check Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "max(pgbackrest_check_success)" }
   ]
  },
  {
   "title": "Archive Failed Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "sum(pg_archiver_failed_count)" }
   ]
  },
  {
   "title": "Replica Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "max(pg_replication_lag)" }
   ]
  }
 ]
}