services:
  pumba:
    image: ${IMG_PUMBA}
    container_name: pumba
    profiles: ["pumba"]
    command: ["--help"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - labnet
